const assultRifles = [
  {
    Name: 'M16',
    Rarity: 'Common',
    DPS: 176,
    Damage: 30,
    'Fire Rate': 5.5,
    Mag: 30,
    Reload: 2.3,
  },
  {
    Name: 'M16',
    Rarity: 'Uncommon',
    DPS: 181.5,
    Damage: 31,
    'Fire Rate': 5.5,
    Mag: 30,
    Reload: 2.2,
  },
  {
    Name: 'M16',
    Rarity: 'Rare',
    DPS: 192.5,
    Damage: 33,
    'Fire Rate': 5.5,
    Mag: 30,
    Reload: 2.2,
  },
  {
    Name: 'SCAR',
    Rarity: 'Epic',
    DPS: 203.5,
    Damage: 35,
    'Fire Rate': 5.5,
    Mag: 30,
    Reload: 2.2,
  },
  {
    Name: 'SCAR',
    Rarity: 'Legendary',
    DPS: 214.5,
    Damage: 36,
    'Fire Rate': 5.5,
    Mag: 30,
    Reload: 2.1,
  },
  {
    Name: 'Burst',
    Rarity: 'Common',
    DPS: 109.7,
    Damage: 27,
    'Fire Rate': 4.06,
    Mag: 30,
    Reload: 2.9,
  },
  {
    Name: 'Burst',
    Rarity: 'Uncommon',
    DPS: 117.9,
    Damage: 29,
    'Fire Rate': 4.06,
    Mag: 30,
    Reload: 2.7,
  },
  {
    Name: 'Burst',
    Rarity: 'Rare',
    DPS: 121.9,
    Damage: 30,
    'Fire Rate': 4.06,
    Mag: 30,
    Reload: 2.6,
  },
  {
    Name: 'Scoped',
    Rarity: 'Rare',
    DPS: 80.5,
    Damage: 23,
    'Fire Rate': 3.5,
    Mag: 20,
    Reload: 2.3,
  },
  {
    Name: 'Scoped',
    Rarity: 'Epic',
    DPS: 84,
    Damage: 24,
    'Fire Rate': 3.5,
    Mag: 20,
    Reload: 2.2,
  },
];

const granadeLaunchers = [
  {
    Name: 'Grenade Launcher',
    Rarity: 'Rare',
    DPS: 100,
    Damage: 100,
    'Fire Rate': 1,
    Mag: 6,
    Reload: 2.9,
  },
  {
    Name: 'Grenade Launcher',
    Rarity: 'Epic',
    DPS: 105,
    Damage: 105,
    'Fire Rate': 1,
    Mag: 6,
    Reload: 2.8,
  },
  {
    Name: 'Grenade Launcher',
    Rarity: 'Legendary',
    DPS: 110,
    Damage: 100,
    'Fire Rate': 1,
    Mag: 6,
    Reload: 2.7,
  },
];

const pistols = [
  {
    Name: 'Revolver',
    Rarity: 'Common',
    DPS: 48.6,
    Damage: 54,
    'Fire Rate': 0.9,
    Mag: 6,
    Reload: 2.4,
  },
  {
    Name: 'Revolver',
    Rarity: 'Uncommon',
    DPS: 51.3,
    Damage: 57,
    'Fire Rate': 0.9,
    Mag: 6,
    Reload: 2.3,
  },
  {
    Name: 'Revolver',
    Rarity: 'Rare',
    DPS: 54,
    Damage: 60,
    'Fire Rate': 0.9,
    Mag: 6,
    Reload: 2.2,
  },
  {
    Name: 'Pistol',
    Rarity: 'Common',
    DPS: 155.2,
    Damage: 23,
    'Fire Rate': 6.75,
    Mag: 16,
    Reload: 1.5,
  },
  {
    Name: 'Pistol',
    Rarity: 'Uncommon',
    DPS: 162,
    Damage: 24,
    'Fire Rate': 6.75,
    Mag: 16,
    Reload: 1.5,
  },
  {
    Name: 'Pistol',
    Rarity: 'Rare',
    DPS: 168.7,
    Damage: 25,
    'Fire Rate': 6.75,
    Mag: 16,
    Reload: 1.4,
  },
];

const rocketLaunchers = [
  {
    Name: 'Rocket',
    Rarity: 'Rare',
    DPS: 82.5,
    Damage: 110,
    'Fire Rate': 0.75,
    Mag: 1,
    Reload: 1.8,
  },
  {
    Name: 'Rocket',
    Rarity: 'Epic',
    DPS: 87,
    Damage: 116,
    'Fire Rate': 0.75,
    Mag: 1,
    Reload: 1.7,
  },
  {
    Name: 'Rocket',
    Rarity: 'Legendary',
    DPS: 90.7,
    Damage: 121,
    'Fire Rate': 0.75,
    Mag: 1,
    Reload: 1.6,
  },
];

const shotguns = [
  {
    Name: 'Pump Shotgun',
    Rarity: 'Common',
    DPS: 63,
    Damage: 90,
    'Fire Rate': 0.7,
    Mag: 5,
    Reload: 4.8,
  },
  {
    Name: 'Pump Shotgun',
    Rarity: 'Uncommon',
    DPS: 66.5,
    Damage: 95,
    'Fire Rate': 0.7,
    Mag: 5,
    Reload: 4.6,
  },
  {
    Name: 'Tactical Shotgun',
    Rarity: 'Uncommon',
    DPS: 100.5,
    Damage: 67,
    'Fire Rate': 1.5,
    Mag: 8,
    Reload: 6.3,
  },
  {
    Name: 'Tactical Shotgun',
    Rarity: 'Rare',
    DPS: 105,
    Damage: 70,
    'Fire Rate': 1.5,
    Mag: 8,
    Reload: 6,
  },
  {
    Name: 'Tactical Shotgun',
    Rarity: 'Epic',
    DPS: 111,
    Damage: 74,
    'Fire Rate': 1.5,
    Mag: 8,
    Reload: 6,
  },
];

const sniperRifles = [
  {
    Name: 'Bolt-Action (AWP)',
    Rarity: 'Rare',
    DPS: 34.7,
    Damage: 105,
    'Fire Rate': 0.33,
    Mag: 1,
    Reload: 3,
  },
  {
    Name: 'Bolt-Action (AWP)',
    Rarity: 'Epic',
    DPS: 36.3,
    Damage: 110,
    'Fire Rate': 0.33,
    Mag: 1,
    Reload: 2.8,
  },
  {
    Name: 'Bolt-Action (AWP)',
    Rarity: 'Legendary',
    DPS: 38.3,
    Damage: 116,
    'Fire Rate': 0.33,
    Mag: 1,
    Reload: 2.7,
  },
  {
    Name: 'Semi-Auto',
    Rarity: 'Epic',
    DPS: 75.6,
    Damage: 63,
    'Fire Rate': 1.2,
    Mag: 10,
    Reload: 2.5,
  },
  {
    Name: 'Semi-Auto',
    Rarity: 'Legendary',
    DPS: 79.2,
    Damage: 66,
    'Fire Rate': 1.2,
    Mag: 10,
    Reload: 2.3,
  },
];

const smgs = [
  {
    Name: 'Suppressor',
    Rarity: 'Common',
    DPS: 153,
    Damage: 17,
    'Fire Rate': 9,
    Mag: 30,
    Reload: 2.2,
  },
  {
    Name: 'Suppressor',
    Rarity: 'Uncommon',
    DPS: 162,
    Damage: 18,
    'Fire Rate': 9,
    Mag: 30,
    Reload: 2.1,
  },
  {
    Name: 'Suppressor',
    Rarity: 'Rare',
    DPS: 171,
    Damage: 19,
    'Fire Rate': 9,
    Mag: 30,
    Reload: 2,
  },
  {
    Name: 'Tactical Sub',
    Rarity: 'Common',
    DPS: 140,
    Damage: 14,
    'Fire Rate': 10,
    Mag: 30,
    Reload: 2.4,
  },
  {
    Name: 'Tactical Sub',
    Rarity: 'Rare',
    DPS: 150,
    Damage: 15,
    'Fire Rate': 10,
    Mag: 30,
    Reload: 2.3,
  },
  {
    Name: 'Tactical Sub',
    Rarity: 'Epic',
    DPS: 160,
    Damage: 16,
    'Fire Rate': 10,
    Mag: 30,
    Reload: 2.2,
  },
  {
    Name: 'Minigun',
    Rarity: 'Epic',
    DPS: 192,
    Damage: 16,
    'Fire Rate': 12,
    Mag: 0,
    Reload: 4.7,
  },
  {
    Name: 'Minigun',
    Rarity: 'Legendary',
    DPS: 204,
    Damage: 17,
    'Fire Rate': 12,
    Mag: 0,
    Reload: 4.5,
  },
];

const archieveWeapons = [
  {
    Name: 'SMG',
    Rarity: 'Common',
    DPS: 150,
    Damage: 10,
    'Fire Rate': 15,
    Mag: 25,
    Reload: 2.5,
  },
  {
    Name: 'SMG',
    Rarity: 'Uncommon',
    DPS: 150,
    Damage: 10,
    'Fire Rate': 15,
    Mag: 25,
    Reload: 2.4,
  },
  {
    Name: 'SMG',
    Rarity: 'Rare',
    DPS: 165,
    Damage: 11,
    'Fire Rate': 15,
    Mag: 25,
    Reload: 2.3,
  },
];

const weapons = [
  {
    shotguns,
  },
  {
    pistols,
  },
  {
    smgs,
  },
  {
    assultRifles,
  },
  {
    sniperRifles,
  },
  {
    granadeLaunchers,
  },
  {
    rocketLaunchers,
  },
  {
    archieveWeapons,
  },
];

export default weapons;
